<a href="https://colab.research.google.com/github/Gaurav2912/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import library
import numpy as np
import pandas as pd

**1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.**


In [2]:
# arr = np.array([i for i in range(6)])
arr = np.linspace(0,5,6, endpoint=True, dtype= int)
print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int64


**2.Given a NumPy array 'arr', check if its data type is float64.**

In [3]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


**3.create a numpy arr with  3 complex numbers with datatype of complex128**

In [4]:
arr = np.array([1.0+2.0j, 3.0+4.0j, 5.0+6.0j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


**4.Convert an existing NumPy array 'arr' of integers to float32 data type.**

In [5]:

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

# Convert the array to float32 uding astype
arr = arr.astype(np.float32)

print(arr)
print(arr.dtype)


int64
[1. 2. 3. 4. 5.]
float32


**5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.**

In [6]:
arr = np.array([1.5, 2.6, 3.7, 4.8, 5.9, 6.0200001])
print("Original array:")
print(arr)
print("Data type of the said array:")
print(arr.dtype)
result = arr.astype(np.float32)
print("Array after converting float64 to float32:")
print(result)
print("Data type of the said array:")
print(result.dtype)


Original array:
[1.5       2.6       3.7       4.8       5.9       6.0200001]
Data type of the said array:
float64
Array after converting float64 to float32:
[1.5  2.6  3.7  4.8  5.9  6.02]
Data type of the said array:
float32


**6)Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.**

In [7]:
def array_attributes(arr: np.array):
  return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 4, 9], [3, 9, 0]])

arr_shape, arr_size, arr_dtype = array_attributes(arr)
#
print(f"shape is : {arr_shape}")
print(f"array size (no. of elements) is : {arr_size}")
print(f"and data type is : {arr_dtype}")

shape is : (2, 3)
array size (no. of elements) is : 6
and data type is : int64


**7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.**

In [8]:
def array_dimension(arr: np.array):
    """
    Function to return the dimensionality of a NumPy array.
    """
    return arr.ndim

array = np.random.rand(3, 4, 5, 9)
dimensionality = array_dimension(array)

print("Dimensionality of the array:", dimensionality)

Dimensionality of the array: 4


**8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.**

In [9]:
def item_size_info(arr):
    """
    Function to return the item size and total size of a NumPy array.
    """
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size


array = np.random.rand(3, 4)
item_size, total_size = item_size_info(array)
print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)

Item size (bytes): 8
Total size (bytes): 96


**9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.**

In [10]:
def array_strides(arr):
    """
    Function to return the strides of a NumPy array.
    """
    return arr.strides # will alos give the same ans

array = np.arange(12, dtype=np.int32).reshape((3, 4))
strides = array_strides(array)

print("Strides of the array:", strides)

Strides of the array: (16, 4)


In [11]:
# dtype in int32 ie 4 bytes
# we have to skip 4 bytes (1 value) to move to the next column, but 16 bytes (5 values) to get to the same position in the next row.
# As such, the strides for the array x will be (16, 4).
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

**10. Design a function `shape_stride_relationship` that takes a NumPy array as input and returns the shape
and strides of the array..**

In [12]:
def shape_stride_relationship(array):
  """ Function to return the strides of a NumPy array."""
  return array.shape , array.strides


arr_shape, arr_stride =  shape_stride_relationship(array)
print(f"Shape of array is : {arr_shape}")
print(f"Stride of array is : {arr_stride}")

Shape of array is : (3, 4)
Stride of array is : (16, 4)


**11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.**

In [13]:
def create_zeros_array(n):
    """
    Function to create a NumPy array of zeros with n elements.
    """
    return np.zeros(n)

n = 5  # Number of elements
zeros_array = create_zeros_array(n)
print("Zeros array: ", zeros_array)

Zeros array:  [0. 0. 0. 0. 0.]


12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [14]:
def create_ones_matrix(rows, cols):
  return np.ones((rows, cols))

print(create_ones_matrix(2, 3))

[[1. 1. 1.]
 [1. 1. 1.]]


13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [15]:
def genrate_range_array(start, stop, steps):
  return np.arange(start, stop, steps)

print(genrate_range_array(12, 85, 11))

[12 23 34 45 56 67 78]


**14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).**

In [16]:
def genrate_linear_space(start, stop, num):
  return np.linspace(start, stop, num)

print(genrate_linear_space(2.0,3.0,5))

[2.   2.25 2.5  2.75 3.  ]


15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [17]:
def create_identity_matix(n):
    return np.eye(n)

print(create_identity_matix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


16. Write a function that takes a Python list and converts it into a NumPy array.

In [18]:
def list2array(l):
  return np.asarray(l)

print(list2array([1,2,3,4]))
print(type(list2array([1,2,3,4])))

[1 2 3 4]
<class 'numpy.ndarray'>



17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [19]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Create a new array object with the same data using numpy.view
view_arr = arr.view()

# Verify that the data is the same
print("Original array:", arr)
print("View array:", view_arr)

# Modify the original array
arr[0] = 10

# Verify that the view array is also modified
print("Modified original array:", arr)
print("Modified view array:", view_arr)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified original array: [10  2  3  4  5]
Modified view array: [10  2  3  4  5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [20]:
def concatinate(arr1, arr2, axis):
    ans = np.concatenate((arr1, arr2), axis)
    return ans

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy
concatenate`.

In [21]:
a = np.array([[1,3], [4,7]])
b = np.array([[7,0]])
concatinate(a, b, 0)

array([[1, 3],
       [4, 7],
       [7, 0]])

20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [22]:
a = np.array([[1,3], [4,7]])
c = np.array([[7], [0]])
concatinate(a, c, 1)

array([[1, 3, 7],
       [4, 7, 0]])

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [23]:
start = 1
stop = 26
step = 5
np.arange(start, stop+1, step)

array([ 1,  6, 11, 16, 21, 26])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [24]:
# 10 linerly spaced values from 0 to 1
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).


In [25]:
np.logspace(0, 3, 5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.


In [26]:
arr = np.random.randint(low=1, high=101, size=(5, 3), dtype=int)
df = pd.DataFrame(arr, columns= ["col1", "col2", "col3"])
df

col1  col2  col3
0    34     2    80
1     1    50    36
2    27    81    86
3    98     7    96
4    81    29    50

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [27]:
def replace_negative_values(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
  return df

# Example usage
df = pd.DataFrame({'A': [-1, 2, -3, 4, -5], 'B': [6, 7, 8, 9, 10]})

df = replace_negative_values(df, 'A')

print(df)

   A   B
0  0   6
1  2   7
2  0   8
3  4   9
4  0  10


26. Access the 3rd element from the given NumPy array.

In [28]:
arr = np.array([10, 20, 30, 40, 50])
# third element at 2nd index
arr[2]

30

27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [29]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[1,2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [30]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# from index 2 to 5
arr[2:6]

array([3, 4, 5, 6])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
<br>

 ```
 arr_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
```



In [32]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.



In [34]:
def extract_elements(array, indices):
     # Ensure indices are integer type
    indices = indices.astype(int)

    # Extract elements using advanced indexing
    extracted_elements = array[indices[:, 0], indices[:, 1]]

    return extracted_elements

# Example usage
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])

extracted_elements = extract_elements(array, indices)
print(extracted_elements)

[2 6 7]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [35]:
def filter_elements(arr, threshold):
  return arr[arr>threshold]

filter_elements(np.array([1, 2, 3, 4, 5]), 3)

array([4, 5])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [36]:
def extract_elements_3d(array, x_indices, y_indices, z_indices):

    # Ensure indices are integer type
    x_indices = x_indices.astype(int)
    y_indices = y_indices.astype(int)
    z_indices = z_indices.astype(int)

    # Extract elements using advanced indexing
    extracted_elements = array[x_indices, y_indices, z_indices]

    return extracted_elements

# Example usage
array = np.arange(27).reshape(3, 3, 3)
x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 2, 0])
z_indices = np.array([2, 0, 1])

extracted_elements = extract_elements_3d(array, x_indices, y_indices, z_indices)
print(extracted_elements)

[ 5 15 19]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [37]:
def conditions(array, condition1, condition2):

    # Bothe condition should satisfied
    extracted_elements = array[condition1 & condition2]

    return extracted_elements

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
condition1 = array > 2
condition2 = array % 2 == 0

extracted_elements = conditions(array, condition1, condition2)
print(extracted_elements)

[4 6 8]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [38]:
def extract_elements_by_indices(array, row_indices, col_indices):

    if row_indices.shape != col_indices.shape:
        raise ValueError("row_indices and col_indices must have the same length")

    # Extract elements using advanced indexing
    extracted_elements = array[row_indices, col_indices]

    return extracted_elements

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

extracted_elements = extract_elements_by_indices(array, row_indices, col_indices)
print(extracted_elements)

[2 6 7]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [39]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [40]:
arr1 = np.array([[10,20,30]])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# first row of arr2 to arr1[0]
# 2nd row to arr1[1]
# 3rd row of arr2 to arr1[2]
arr2*arr1.T

array([[ 10,  20,  30,  40],
       [100, 120, 140, 160],
       [270, 300, 330, 360]])


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [41]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[10,20, 30],[40, 50, 60], [70, 80, 90], [100, 110,  120]])
arr2+arr1.T

array([[ 11,  21,  31],
       [ 42,  52,  62],
       [ 73,  83,  93],
       [104, 114, 124]])

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.de




In [42]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[10], [20], [30]])
arr1+arr2

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [43]:
# Given arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

arr2_reshaped = arr2[:, :, np.newaxis]

result = arr1[:, np.newaxis, :] * arr2_reshaped

print(result)

[[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


41. Calculate column wise mean for the given array.

In [44]:
arr = np.array([[1,4,7], [2,5,8], [3,6,9]])
# mean "across" axis 0 is column wise mean
np.mean(arr, axis=0)

array([2., 5., 8.])

42. Find maximum value in each row of the given array.

In [45]:
np.max(arr, axis=1)

array([7, 8, 9])

43. For the given array, find indices of maximum value in each column.


In [47]:
np.argmax(arr, axis=0) #

array([2, 2, 2])


44. For the given array, apply custom function to calculate moving sum along rows.

45. In the given array, check if all elements in each column are even.

```
arr = np.array([[1, 2, 3], [4, 5, 6]])
```


In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Check if all elements in each column are even
np.all(arr % 2 == 0, axis=0)

array([False, False, False])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.


In [50]:
def reshape_matrix(arr, m, n):
  return arr.reshape(m, n)

reshape_matrix(np.arange(1, 13), 3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

47. Create a function that takes a matrix as input and returns the flattened array.

In [51]:
def flatten_matrix(matrix):
  return matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flatten_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

48. Write a function that concatenates two given arrays along a specified axis.

In [52]:
def concatinate(arr1, arr2, axis):
  return np.concatenate((arr1, arr2), axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatinate(a, b, 0)

array([[1, 3],
       [4, 7],
       [7, 0]])

49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [53]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

num_splits = 2
split_array = np.array_split(original_array, num_splits, axis=1)
for arr in split_array:
    print(arr)
    print()

[[1 2]
 [4 5]
 [7 8]]

[[3]
 [6]
 [9]]



50. Write a function that inserts and then deletes elements from a given array at specified indices.

```
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
```

In [54]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
  # Insert elements
  new_array = np.insert(original_array, indices_to_insert, values_to_insert)

  # Delete elements
  new_array = np.delete(new_array, indices_to_delete)

  return new_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

new_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print(new_array)


[ 1 10  4 11  5]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [55]:
arr1 = np.random.randint(1, 101, size=(10,))
arr2 = np.arange(1, 11)

result = arr1 + arr2
print(result)

[96 24 16 46 31 11 93 56 46 49]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [56]:
arr1 = np.arange(10, 0,-1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print("arr1 is ",arr1)
print("arr2 is ",arr2)
print("result is ",result)

arr1 is  [10  9  8  7  6  5  4  3  2  1]
arr2 is  [ 1  2  3  4  5  6  7  8  9 10]
result is  [ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [57]:
arr1 = np.random.randint(1, 101, size=(5,))
arr2 = np.arange(1, 6)

result = arr1 * arr2
print("arr1 is ",arr1)
print("arr2 is ",arr2)
print("result is ",result)

arr1 is  [49 50 25 79 87]
arr2 is  [1 2 3 4 5]
result is  [ 49 100  75 316 435]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [58]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2
print("arr1 is ",arr1)
print("arr2 is ",arr2)
print("result is ",result)

arr1 is  [ 2  4  6  8 10]
arr2 is  [1 2 3 4 5]
result is  [2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

In [59]:
arr1 = np.arange(1, 6)
arr2 = np.arange(5, 0,-1)
result = arr1 ** arr2
print("arr1 is ", arr1)
print("arr2 is ", arr2)
print("result is " ,result)

arr1 is  [1 2 3 4 5]
arr2 is  [5 4 3 2 1]
result is  [ 1 16 27 16  5]



56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [61]:
def count_substring_occurrences(arr, substring):
    # elem will one if it is substring  else 0
    occurrences = np.char.count(arr, substring)
    total_occurrences = np.sum(occurrences)

    return total_occurrences

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = "world"

total_occurrences = count_substring_occurrences(arr, substring)
print(total_occurrences)


1


57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])


In [62]:
def extract_uppercase(arr):
  arr_list = arr.tolist()
  uppercase_chars = []

  for string in arr_list:
    for char in string:
      if char.isupper():
        uppercase_chars.append(char)
  return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']



58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [63]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
replaced_strings = np.char.replace(arr, old_substring, new_substring)
print(replaced_strings)

['orange' 'banana' 'grape' 'pineorange']


59. Write a function that concatenates strings in a NumPy array element-wise.

In [64]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Use numpy.char.add to concatenate strings element-wise
concatenated_array = np.char.add(arr1, arr2)
print(concatenated_array)

['HelloOpen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.



In [65]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
string_lengths = np.char.str_len(arr)

# Find the maximum length
max_length = np.max(string_lengths)
print(max_length)

9


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [66]:
import numpy as np

# Generate the dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset) # np.sqrt(variance)

# Print the results
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Dataset: [465 928  93 989 725 606 289 666 971 732  27  14  79 683 750 552 623 482
 918 303 381 321 257 513 864 587 636 176 374 538 855 595 476  12  10 999
 808 737 131 423 125 210 995  92 588 176 219 902 687 540 900 158  56 851
  66 322 746 635 537 748 355 183  17 645  57 535 974 175 523 715 445 392
 357 432 569 834 732 872 686  45 617 519 652 786 279 681 883 665 609 587
 192 166 870 130 392 661 240 492 931 513]
Mean: 505.49
Median: 537.5
Variance: 81934.86989999999
Standard Deviation: 286.2426765875417


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [67]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles of the dataset
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Print the results
print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset: [59 48 39 57 13 12  9  7 52 68 49 70 24 18 94 93 35 80 51 26 39 98 22 60
 55 42 41 30 31 49 55 93 37 34 52 69 81 21 76  7 63 53 56 32  8 46 46 62
 22 41]
25th Percentile: 30.25
75th Percentile: 59.75


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [74]:
import numpy as np

array1 = np.random.randint(0, 101, size=10)
array2 = np.random.randint(0, 101, size=10)

correlation_matrix = np.corrcoef(array1, array2)

print(correlation_matrix)

correlation_coefficient = correlation_matrix[0, 1] #

print(f"The correlation coefficient between the two arrays is: {correlation_coefficient:.2f}")

[[1.         0.18058393]
 [0.18058393 1.        ]]
The correlation coefficient between the two arrays is: 0.18


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [77]:
import numpy as np

matrix1 = np.random.randint(0, 10, size=(3, 3))
matrix2 = np.random.randint(0, 10, size=(3, 3))

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

# Display the matrices and the result
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)


Matrix 1:
[[2 1 2]
 [5 7 0]
 [6 1 1]]

Matrix 2:
[[8 4 9]
 [9 4 4]
 [0 1 8]]

Result of Matrix Multiplication:
[[ 25  14  38]
 [103  48  73]
 [ 57  29  66]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [82]:
array = np.random.randint(10, 1001, size=50)

percentile_10th = np.percentile(array, 10)
median = np.percentile(array, 50)
percentile_90th = np.percentile(array, 90)
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print(f"Array: {array}")
print()
print(f"sorted form of array is : {np.sort(array)}")
print()
print(f"10th Percentile: {percentile_10th}")
print(f"First Quartile: {first_quartile}")
print(f"50th Percentile (Median): {median}")
print(f"Third Quartile: {third_quartile}")
print(f"90th Percentile: {percentile_90th}")

Array: [982 485 572 577 221 478 113 174 472 262 951 183 278 928 500 635 604 115
 740 863 706 856 333 991 147 555 474 320 493 804 764 593 127 528 761 209
 112 374  36 126 974 623 902 199 586  33 115 100 880 495]

sorted form of array is : [ 33  36 100 112 113 115 115 126 127 147 174 183 199 209 221 262 278 320
 333 374 472 474 478 485 493 495 500 528 555 572 577 586 593 604 623 635
 706 740 761 764 804 856 863 880 902 928 951 974 982 991]

10th Percentile: 114.8
First Quartile: 201.5
50th Percentile (Median): 494.0
Third Quartile: 731.5
90th Percentile: 904.6


66. Create a NumPy array of integers and find the index of a specific element.


In [84]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 50, 100])

element_to_find = 50


indices = np.where(array == element_to_find)

print("Array:", array)
print(f"Index of element {element_to_find}:", indices[0])

Array: [ 10  20  30  40  50  60  70  80  50 100]
Index of element 50: [4 8]


67. Generate a random NumPy array and sort it in ascending order.


In [86]:
array = np.random.randint(0, 100, size=10)

# Sort the array in ascending order
sorted_array = np.sort(array)

# Print the original and sorted arrays
print("Original array:", array)
print("Sorted array:", sorted_array)

Original array: [70 39 22 12  7 92 17 37 27 86]
Sorted array: [ 7 12 17 22 27 37 39 70 86 92]


68. Filter elements >20  in the given NumPy array.


In [89]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

69. Filter elements which are divisible by 3 from a given NumPy array.


In [90]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.


In [91]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])


71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [95]:
arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)

Byte Order: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [96]:
# Perform byte swapping in place
arr.byteswap(True)

print("Byte swapped array:", arr)

Byte swapped array: [ 72057594037927936 144115188075855872 216172782113783808]



73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

In [97]:
# Swap byte order without modifying the original array
arr_swapped = arr.newbyteorder()

print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)

Original array: [ 72057594037927936 144115188075855872 216172782113783808]
Array with swapped byte order: [1 2 3]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

In [98]:
import sys

# Swap byte order conditionally based on system endianness
if sys.byteorder == 'little':
    arr_swapped = arr.newbyteorder('big')
else:
    arr_swapped = arr.newbyteorder('little')

print("Original array:", arr)
print("Array with swapped byte order based on system endianness:", arr_swapped)


Original array: [ 72057594037927936 144115188075855872 216172782113783808]
Array with swapped byte order based on system endianness: [1 2 3]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

In [99]:
# Check if byte swapping is necessary for the current system
if arr.dtype.byteorder == sys.byteorder:
    print("Byte swapping is not necessary for the current system.")
else:
    print("Byte swapping is necessary for the current system.")

Byte swapping is necessary for the current system.


76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [100]:
# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


We can see heare that original array is not changed.

77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [101]:
matrix = np.random.randint(0, 100, size=(3, 3))

# Extract a slice view from the matrix
view_slice = matrix[:2, :2]

# Print original matrix and the slice view
print("Original Matrix:")
print(matrix)
print("\nSlice View:")
print(view_slice)

# Modify an element in the slice view
view_slice[0, 0] = 999

# Print the modified slice view and the original matrix
print("\nModified Slice View:")
print(view_slice)
print("\nOriginal Matrix After Modification:")
print(matrix)

Original Matrix:
[[24 30 37]
 [88 10 33]
 [79 88 62]]

Slice View:
[[24 30]
 [88 10]]

Modified Slice View:
[[999  30]
 [ 88  10]]

Original Matrix After Modification:
[[999  30  37]
 [ 88  10  33]
 [ 79  88  62]]


we can see that it modifies original matrix.

78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [103]:
import numpy as np

# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

print("Original array_a before:")
print(array_a)

# Extract a slice view view_b from array_a
view_b = array_a[:2, :2]

# Broadcast the addition of 5 to view_b
view_b += 5

# Check if it alters the original array_a
print("Original array_a after:")
print(array_a)


Original array_a before:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Original array_a after:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


It modified original array.


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.



In [104]:
# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Print original orig_array and the reshaped_view
print("Original orig_array:")
print(orig_array)
print("\nReshaped View:")
print(reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Print the modified reshaped_view and the original orig_array
print("\nModified Reshaped View:")
print(reshaped_view)
print("\nOriginal orig_array After Modification:")
print(orig_array)

Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified Reshaped View:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original orig_array After Modification:
[[100   2   3   4]
 [  5   6   7   8]]


It modifies original array

80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [108]:
# Create a NumPy array data of shape (3, 4) with random integers
data = np.random.randint(0, 10, size=(3, 4))

# Extract a copy data_copy of elements greater than 5
data_copy = data[data > 5]

# Print original data and the copy data_copy
print("Original data:")
print(data)
print("\nCopy data_copy of elements greater than 5:")
print(data_copy)

# Modify an element in data_copy
data_copy[0] = 100

# Verify if it affects the original data
print("\nModified data_copy:")
print(data_copy)
print("\nOriginal data After Modification:")
print(data)


Original data:
[[4 3 3 2]
 [8 6 0 6]
 [6 7 3 7]]

Copy data_copy of elements greater than 5:
[8 6 6 6 7 7]

Modified data_copy:
[100   6   6   6   7   7]

Original data After Modification:
[[4 3 3 2]
 [8 6 0 6]
 [6 7 3 7]]


Original array is unchanged

81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [109]:
import numpy as np

# Define the shape of the matrices
shape = (3, 3)

# Create matrix A with random integers
A = np.random.randint(1, 10, size=shape)

# Create matrix B with random integers
B = np.random.randint(1, 10, size=shape)

# Perform addition between matrices A and B
addition_result = A + B

# Perform subtraction between matrices A and B
subtraction_result = A - B

# Print the matrices and the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition result (A + B):")
print(addition_result)
print("\nSubtraction result (A - B):")
print(subtraction_result)

Matrix A:
[[4 4 9]
 [3 9 9]
 [6 7 9]]

Matrix B:
[[1 9 7]
 [9 5 2]
 [6 5 8]]

Addition result (A + B):
[[ 5 13 16]
 [12 14 11]
 [12 12 17]]

Subtraction result (A - B):
[[ 3 -5  2]
 [-6  4  7]
 [ 0  2  1]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [112]:
# Generate matrix C (3x2) with random integers
C = np.random.randint(1, 10, size= (3,2))

# Generate matrix D (2x4) with random integers
D = np.random.randint(1, 10, size=(2,4))

# Perform matrix multiplication between matrices C and D
multiplication_result = np.dot(C, D) # C@D

# Print the matrices and the result of the multiplication
print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of matrix multiplication (C @ D):")
print(multiplication_result)

Matrix C (3x2):
[[2 4]
 [3 3]
 [4 4]]

Matrix D (2x4):
[[6 1 5 8]
 [6 4 9 7]]

Result of matrix multiplication (C @ D):
[[36 18 46 44]
 [36 15 42 45]
 [48 20 56 60]]


83. Create a matrix `E` and find its transpose.

In [114]:
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

E_transpose = np.transpose(E)

print("Matrix E:")
print(E)
print("\nTranspose of matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]



84. Generate a square matrix `F` and compute its determinant.


In [121]:
# Generate a square matrix F (let's say 3x3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix F and its determinant
print("Matrix F:")
print(F)
print("\nDeterminant of matrix F: {:.2f}".format(determinant_F))

Matrix F:
[[3 9 1]
 [8 8 9]
 [9 9 7]]

Determinant of matrix F: 150.00








85. Create a square matrix `G` and find its inverse.

In [122]:
# Generate a square matrix G (let's say 3x3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Find the inverse of matrix G
inverse_G = np.linalg.inv(G)

# Print the matrix G and its inverse
print("Matrix G:")
print(G)
print("\nInverse of matrix G:")
print(inverse_G)

Matrix G:
[[7 8 3]
 [5 8 6]
 [8 5 3]]

Inverse of matrix G:
[[-0.05714286 -0.08571429  0.22857143]
 [ 0.31428571 -0.02857143 -0.25714286]
 [-0.37142857  0.27619048  0.15238095]]
